[package]
name = "cogate-cotab-proto"
version = "0.1.0"
edition = "2021"
description = "Versioned protobuf contracts for the cogate platform"
license = "MIT"
repository = "https://github.com/brojyf/cogate-cotab-proto"

[dependencies]
prost = "0.13"
tonic = "0.13"

[build-dependencies]
tonic-build = "0.13"
